#! /usr/bin/env python
# encoding: utf-8

cxxflags = []
compiler_binary = bld.env.get_flat("CXX").lower()
if "clang" in compiler_binary:
    cxxflags = ["-fconstexpr-steps=1000000000"]
elif "cl.exe" in compiler_binary:
    cxxflags = ["/constexpr:steps1000000000"]

bld.program(
    features="cxx test",
    source=["fifi_tests.cpp"] + bld.path.ant_glob("src/**/*.cpp"),
    target="fifi_tests",
    cxxflags=cxxflags,
    install_path=None,
    use=["fifi", "gtest", "stub_includes", "abacus"],
)
